version: '3.8'

services:
  backend:
    build: .
    container_name: pilla-multa-backend
    ports:
      - '3001:3001'
    environment:
      - DB_URI=mongodb://mongo:27017/pilla-multa
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3001
      - LITELLM_URL=http://host.docker.internal:4000 # To reuse LiteLLM running on host
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: pilla-multa-mongo
    ports:
      - '27018:27017'
    volumes:
      - pilla-multa-mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: pilla-multa-redis
    ports:
      - '6380:6379'
    volumes:
      - pilla-multa-redis-data:/data

volumes:
  pilla-multa-mongo-data:
  pilla-multa-redis-data:
